apiVersion: v1
kind: Service
metadata:
  name: oxidized-svc
  labels:
        app: oxidized
spec:
  ports:
  - port: 8888
  clusterIP: None
  selector:
    app: oxidized
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxidized
spec:
  selector:
    matchLabels:
      app: oxidized
  serviceName: oxidized-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: oxidized
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: oxidized
        image: ghcr.io/mapickett/oxidized:latest
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /home/oxidized/.config/oxidized
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oxidized-ing
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: oxidized.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oxidized-svc
            port:
              number: 8888
