apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxidized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxidized
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: oxidized
    spec:
      containers:
      - name: oxidized
        image: ghcr.io/mapickett/oxidized:latest
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: oxidized-svc
spec:
  type: ClusterIP
  selector:
    app: oxidized
  ports:
  - port: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oxidized-ing
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: oxidized.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oxidized-svc
            port:
              number: 8888
